### ISSUE TITLE
Crash when clicking on a SGPU when iris is closed on a stargate.

### ISSUE THREAD

**Issue by messra20** [StargateMC/Server#63] opened 2015-03-10 14:20 UTC
Crash when clicking on a SGPU when iris is closed on a stargate.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/10/15 10:15 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['messra20'/383310, l='MpServer', x=234.72, y=37.62, z=790.58], MCH_ViewEntityDummy['MissingName'/232, l='MpServer', x=222.50, y=70.62, z=662.50]]
	Chunk stats: MultiplayerChunkCache: 377, 377
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (222,68,662), Chunk: (at 14,4,6 in 13,41; contains blocks 208,0,656 to 223,255,671), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 28146463 game time, 28813310 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 42 total; [EntityCrab['Crab'/194, l='MpServer', x=257.25, y=60.00, z=780.47], EntityItem['item.item.CrabLegs'/386179, l='MpServer', x=257.19, y=60.13, z=780.22], IrisEntity['entity.SGCraft.Stargate Iris.name'/383311, l='MpServer', x=234.50, y=41.50, z=789.50], EntityBat['Bat'/391627, l='MpServer', x=281.44, y=44.70, z=813.63], EntityBat['Bat'/391626, l='MpServer', x=283.09, y=45.32, z=810.69], EntityItem['item.item.dyePowder.black'/383317, l='MpServer', x=221.81, y=60.13, z=808.97], EntityItem['item.item.CrabLegs'/383316, l='MpServer', x=254.34, y=61.13, z=790.88], EntityItem['item.item.CrabLegs'/383319, l='MpServer', x=270.63, y=70.13, z=792.13], EntityCrab['Crab'/383318, l='MpServer', x=271.25, y=66.00, z=801.41], BlueSlime['Blue Slime'/383313, l='MpServer', x=253.56, y=61.00, z=788.80], EntityCrab['Crab'/383312, l='MpServer', x=254.53, y=61.00, z=790.85], EntityItem['item.item.CrabLegs'/383315, l='MpServer', x=252.06, y=60.13, z=784.97], EntityCrab['Crab'/383314, l='MpServer', x=249.72, y=60.00, z=784.44], EntityZombie['Zombie'/383325, l='MpServer', x=187.69, y=42.00, z=787.31], EntityZombie['Zombie'/383324, l='MpServer', x=185.50, y=41.00, z=788.97], EntityZombie['Zombie'/383327, l='MpServer', x=181.97, y=45.00, z=785.67], GCEntityClientPlayerMP['messra20'/383310, l='MpServer', x=234.72, y=37.62, z=790.58], EntityZombie['Zombie'/383326, l='MpServer', x=181.30, y=45.00, z=785.32], EntityZombie['Zombie'/383321, l='MpServer', x=184.44, y=44.00, z=786.22], BlueSlime['Blue Slime'/383320, l='MpServer', x=217.40, y=41.00, z=830.40], EntityZombie['Zombie'/383323, l='MpServer', x=182.06, y=45.14, z=786.54], EntityZombie['Zombie'/383322, l='MpServer', x=187.52, y=41.00, z=788.66], EntityZombie['Zombie'/383333, l='MpServer', x=179.50, y=34.00, z=791.13], EntityZombie['Zombie'/383332, l='MpServer', x=180.31, y=47.00, z=784.66], EntityZombie['Zombie'/383335, l='MpServer', x=177.31, y=48.00, z=785.53], EntityZombie['Zombie'/383334, l='MpServer', x=180.31, y=46.48, z=786.56], EntityZombie['Zombie'/383329, l='MpServer', x=183.78, y=43.00, z=788.69], EntityZombie['Zombie'/383328, l='MpServer', x=186.47, y=41.00, z=787.78], EntityZombie['Zombie'/383331, l='MpServer', x=186.13, y=41.00, z=789.31], EntityZombie['Zombie'/383330, l='MpServer', x=178.16, y=48.00, z=785.56], MCH_ViewEntityDummy['MissingName'/232, l='MpServer', x=222.50, y=70.62, z=662.50], EntityItem['item.item.CrabLegs'/383343, l='MpServer', x=298.75, y=73.13, z=788.78], EntityWaypointContainer['unknown'/234, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCrab['Crab'/383342, l='MpServer', x=298.34, y=73.00, z=789.28], EntityZombie['Zombie'/383337, l='MpServer', x=174.97, y=38.00, z=804.47], EntityZombie['Zombie'/383336, l='MpServer', x=216.31, y=42.00, z=831.56], EntityZombie['Zombie'/383339, l='MpServer', x=276.70, y=37.00, z=827.70], EntityZombie['Zombie'/383338, l='MpServer', x=176.70, y=11.00, z=821.50], EntityZombie['Zombie'/383345, l='MpServer', x=177.53, y=16.00, z=837.31], IrisEntity['entity.SGCraft.Stargate Iris.name'/187, l='MpServer', x=234.50, y=59.50, z=742.50], EntityCartChest['entity.MinecartChest.name'/188, l='MpServer', x=238.50, y=58.50, z=746.50], EntityItemFrame['entity.ItemFrame.name'/189, l='MpServer', x=233.50, y=66.50, z=753.94]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 534686544 bytes (509 MB) / 1550319616 bytes (1478 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 76 mods loaded, 76 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (nei-1.0.3.74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenEye{0.6} [OpenEye] (openeye-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.680-experimental} [IndustrialCraft 2] (ic2-2.2.680.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ImmibisCore{59.0.7} [Immibis Core] (immibiscore-59.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedMachines{59.0.2} [Advanced Machines] (advancedmachines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems] (advancedrepulsionsystems-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advancedsolarpanels-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics-2b8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (baubles-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0RC1} [CoFH Core] (cofhcore-3.0.0.181.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.4.1} [BuildCraft] (bc-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.4.1} [BC Transport] (bc-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.4.1} [BC Silicon] (bc-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.4.1} [BC Builders] (bc-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.4.1} [BC Energy] (bc-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.4.1} [BC Factory] (bc-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (bibliocraft-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Botania{r1.5-163} [Botania] (botania-1.5.163.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (compactsolars-4.4.39.315.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ComputerCraft{1.7} [ComputerCraft] (computercraft-1.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	customnpcs{1.7.10c} [CustomNpcs] (customnpcs-1.7.10c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	desertcraft{1.7.2b} [Pam's DesertCraft] (desertcraft-1.7.10a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	extendedWorkbench{1.2.1.1} [Extended Workbench] (extendedworkbench-1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	flansmod{4.9.0} [Flan's Mod] (flansmod-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (furnituremod-3.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (galacticraftcore-3.0.8.266.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (galacticraftplanets-3.0.8.266.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (gravisuite-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HoloInventory{1.8.3.86} [HoloInventory] (holoinventory-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LLadders{0.5.0} [Luppii's Ladders] (lupisladders-0.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (mantle-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mcheli{0.9.3} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mediccraft{1.0.1 - 1.7.2} [MedicCraft] (mediccraft-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.5.0.0} [Railcraft] (railcraft-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mekanism{7.1.1} [Mekanism] (mekanism-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Natura{2.2.0} [Natura] (natura-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Oceancraft{1.4.1} [Oceancraft] (oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.6} [OpenMods] (openmodslib-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.3} [OpenBlocks] (openblocks-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Core{4.5.12.64} [ProjectRed] (projectredbase-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transmission{4.5.12.64} [ProjectRed-Transmission] (projectredintegration-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0RC2} [Thermal Foundation] (thermalfoundation-1.0.0.53.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0RC1} [Thermal Expansion] (thermalexpansion-4.0.0.119.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StargateTech2{0.7.7-Alpha} [StargateTech 2] (stargatetech-0.7.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers{1.5.0.6} [OpenComputers] (opencomputers-1.5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Integration{4.5.12.64} [ProjectRed-Integration] (projectredintegration-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Illumination{4.5.12.64} [ProjectRed-Illumination] (projectredlighting-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Expansion{4.5.12.64} [ProjectRed-Expansion] (projectredmechanical-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Transportation{4.5.12.64} [ProjectRed-Transportation] (projectredmechanical-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ProjRed|Exploration{4.5.12.64} [ProjectRed-Exploration] (projectredworld-4.5.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SGCraft{1.9.2} [Greg's SG Craft] (sgcraft-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.7.1.build803} [Tinkers' Construct] (tinkersconstruct-1.7.1d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Treecapitator{1.7.10} [Treecapitator] (treecapitator-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Tubestuff{59.0.3} [Tubestuff] (tubestuff-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	CoFHCore: -[1.7.10]3.0.0RC1-181
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.0.0RC2-53
	ThermalExpansion: -[1.7.10]4.0.0RC1-119
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.18.10.3215, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Ornate-5-RR-LE-1.8.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by messra20** [comment] 2015-03-10 14:52
Ha ha! i figured out why i was crashing when i clicked on the power units the iris being closed caused it to crash when i clicked on the PUs so the iris has to be open otherwise it crashes when you check on the power ha ha send it to greg

**Comment by draksterau** [comment] 2015-03-10 23:50
Greg can't reproduce this.

Try not using a thing except red stone torch (vanilla) to close your iris, and ic2 on your gate and see if you crash.

Might be project red?

**Comment by messra20** [comment] 2015-03-11 17:27
yup its project red im almost sure on it tried it with a red stone torch and a lever no crash but id still possibly greg could fix the issue or you might send it off to whom ever does project red

**Comment by draksterau** [comment] 2015-03-11 21:50
The thing is you haven't identified what causes it, so you can't  send it to anyone.

Figure it hat on out so I can tell them how to reproduce the bug.

**Comment by draksterau** [comment] 2015-03-12 08:41
Closing issue as I can't reproduce it.

**Closed by draksterau** 2015-03-12 08:41 UTC
Labels: Client Crash Bug, Stability/Balancing

**Comment by messra20** [comment] 2015-03-12 14:31
ok well when were both on at the same time again ill show where it happened to me at

**Comment by draksterau** [comment] 2015-03-13 04:05
I don't know the project red developers but can see if they have a new version.
